### PR TITLE
add travis ci

### PR DESCRIPTION
**Pull request by tabanliviu**

### CODE REVIEW

**Comment by tabanliviu** [comment]
@jamiecoombs can you please review? thanks

**Review by jamiecoombs — COMMENTED** [review]
Might be worth experimenting with headless chrome instead of virtual framebuffers. If you can get it to work it should be faster. Take a look at the config here: https://github.com/karma-runner/karma/issues/2603

**Comment by tabanliviu** [comment]
@jamiecoombs I've updated with proposed changes please review

**Review by jamiecoombs — APPROVED** [review]
Looks good!

**Pull request merged**
