### PR TITLE
ISSUE-18 add linting rules

### PR DESCRIPTION
**Pull request by tabanliviu**
see #18

### CODE REVIEW

**Comment by tabanliviu** [comment]
@jamiecoombs please review
I need this to get to development before #17 so we can apply all the style rules there

**Review by jamiecoombs — COMMENTED** [review]
I presume the custom rule set you've added is to bring the rules into line with the version of airbnb that we're using in other projects?
Given that we want to bring the projects into line with the latest version of the standard, do we really need to apply these custom rules here?

**Comment by tabanliviu** [comment]
I've disabled rules that were causing errors on the code that was previously checked against jscs 1.13.1 airbnb. But there might be deviations because it's ES6 and eslint.

In short yes.

**Comment by tabanliviu** [comment]
@jamiecoombs updated with all the linting and cleaned dependencies

**Review by ghost — APPROVED** [review]
Looks good

**Pull request merged**
