### PR TITLE
update travis ci to build development

### PR DESCRIPTION
**Pull request by tabanliviu**

### CODE REVIEW

**Review by jamiecoombs — COMMENTED** [review]
I assume the regex is for release branches in semver format? If so, current release branch is called "release-1.1.0", which wouldn't match (due to start of line anchor)

**Comment by tabanliviu** [comment]
@jamiecoombs yes it's only for 1.0.0 type branches/tags

**Comment by jamiecoombs** [comment]
Sorry, dumb question... when do we use release-1.0.0 vs. simply 1.0.0 ?

**Comment by tabanliviu** [comment]
I needed to create a "release" branch to update the manifest version with a tag as well
I guess I could call it directly 1.0.0 branch then after the merge I'll delete it. But I don't want travis to trigger a build on the branch name AND the tag

**Review by jamiecoombs — APPROVED** [review]
All ok

**Pull request merged**
